import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavigationSection from "@/component/Navbar/Navbar";
import FooterSection from "@/component/Footer/FooterSection";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Hive UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <div>
          <NavigationSection />
          <main>{children}</main>
          <FooterSection />
        </div>
      </body>
    </html>
  );
}
